FROM alpine:latest
RUN curl -LJ -o /usr/local/bin/copy-docker-image https://github.com/jkroepke/copy-docker-image/releases/download/v2.0.0-rc.1/copy-docker-image_linux_amd64
CMD ["/usr/local/bin/copy-docker-image"]